#!/bin/bash
# Update packages
yum update -y

# install Java 17 (Amazon Corretto)
yum install -y java-17-amazon-corretto

# Create app directory
mkdir -p /opt/myapp
cd /opt/myapp

# Download the JAR from S3
echo "Downloading Coupon Service Jar File from S3..."
wget https://joe-oregan-s3.s3.us-east-1.amazonaws.com/couponservice_v3b_book.jar -O /opt/myapp/couponservice_v7.jar

# Run the JAR in the background so it doesn't block boot
echo "Starting Coupon Service..."
nohup java -jar /opt/myapp/couponservice_v7.jar > /opt/myapp/app.log 2>&1 &

# Install http daemon web server
yum install -y httpd

# Use index.html to demo load balancing
wget https://joe-oregan-s3.s3.us-east-1.amazonaws.com/index.html -O /var/www/html/index.html

echo "Starting httpd service..."
service httpd start

# CPU Plan B: Get text file to read to try and make the CPU work
wget https://joe-oregan-s3.s3.us-east-1.amazonaws.com/alice.txt -O /opt/myapp/alice.txt

# Add Stress Utility
yum install -y stress